@startuml DesignClassModel

title Design Class Model

class Character{
  #max_health: int
  #curr_health: int
  #attack: int
  
  +Character()
  +applyDamage()
  +setMaxHealth()
  +setAttackValue()
  +setCurrHealth()
  +getCurrHealth()
  +getMaxHealth()
  +getAttackValue()
}

class Player{
  -playerId: String
  -name: String
  -buff: int
  -curr_Position: int
  -selected: boolean
  
  +Player()
  +heal()
  +equip()
  +unequip()
  +isEquiped()
  +changePosition()
  +getPosition()
  +setPosition()
  +getPlayerId()
  -setPlayerId()
  +getName()
  
}

class Enemy{
  +Enemy()
}

class GameUI{
  -gameManager: GameManager
  -outputBox: TextArea
  
  +start()
  +main()
}

class GameManager{
  -player: Player
  -map: Map
  -monster: Enemy
  -inventory: Inventory
  -enemyFight: boolean
  
  +commandControl()
  +newGame()
  +gameOver()
  +room201()
  +room202()
  +room203()
  +room101()
  +room102()
  +room103()
  +hallway1()
  +hallway2()
  +mainhall()
  +controlRoom()
  +morgue()
  +lift()
  +use()
  +inventory()
}

class GameSaveServices{
  -s3: S3Client
  -bucketName: String
  
  +GameSaveService()
  +saveGame()
  +loadGame()
  +deleteGame()
  +loadGameAsObject()
}

class GameState{
}

class Inventory{
  -inventory: ArrayList<Item>
  
  +addItem()
  +removeItem()
  +searchItem()
}

class Item{
  #name: String
  #description: String
  
  +Item()
  +setDescription()
  +getDescription()
  +getName()
}

class ItemEquipable{
  #stats: int
  
  +ItemEquipable()
  +setStats()
  +getStats()
}

class ItemInteract{
  -display_message: String[]
  
  +setDisplay()
  +Display()
}

class Medicine{
  +Medicine()
  +useMedicine()
}

class Weapon{
  +Weapon()
}

class Map{
  #itemFlag: List<Boolean>
  -rooms: Room[]
  
  +Map()
  +Room()
  +setflag()
  +getFlag()
}

Character <|-- Player : extends
Character <|-- Enemy : extends

Item <|-- ItemEquipable : extends
Item <|-- ItemInteract : extends
Item"0...*" <|-- "1"Inventory : contains
Item"n" <|-- "1"Map : has

ItemEquipable <|-- Weapon: extends
ItemEquipable <|-- Medicine: extends

Player"1" --|> "0...*"Item : uses 
Player"1" --|> "1"Inventory : has
Player"1" --|> "1"Map : explores

GameManager"1" --|> "1"Player : creates
GameManager"1" --|> "n"Enemy : creates
GameManager"1" <|--|> "1"GameUI : uses
GameManager"1" --|> "1"Map : creates
GameManager"1" --|> "1"GameSaveServices : uses
GameSaveServices"1" --|> "1"GameState : uses

@enduml
