@startuml DomainModel

!theme materia-outline

skinparam ArrowColor #DC143C
skinparam BackgroundColor #FFFFFF

skinparam ObjectBorderColor #C41E3A
skinparam ObjectFontColor #831D1C

skinparam titleBorderColor #DC143C
skinparam titleFontColor #DC143C

title Domain Model

object Player {
  max_health
  curr_health
  attack
  curr_Position
  buff
  }
  
object Enemy{
  max_health
  curr_health
  attack
  }

object Game

object Inventory

object Item {
  id
  name
  description
  }

object Map {

  }


Player "1" --> "1" Game: plays
Player "1" --> "*" Enemy: fights
Player "1" --> "1" Map: explores
Player "1" --> "1" Inventory: has
Player "1" --> "*" Item: collects

Game "1" --> "1" Map: has
Item "*" --> "1" Map: present in
Inventory "1" --> "*" Item: carry
Enemy "1" --> "1" Map: present in 

@enduml
