@startuml MoveInternalSequenceDiagram

!theme materia-outline

skinparam ArrowColor #DC143C
skinparam BackgroundColor #FFFFFF

skinparam titleBorderColor #DC143C
skinparam titleFontColor #DC143C

skinparam ActorBorderColor #DC143C
skinparam ActorFontColor #DC143C

skinparam ParticipantFontColor #DC143C
skinparam ParticipantBorderColor #DC143C

skinparam SequenceGroupBorderColor #DC143C

title Move - Internal Sequence Diagram

actor User
participant GameUI
participant GameManager
participant Player

activate GameUI
User -> GameUI : input "move" command

activate GameManager
GameUI -> GameManager : commandControl("move")

activate Player
GameManager -> Player : getposition()
Player --> GameManager : return the position of the Player
GameManager -> GameManager : room move operation
  alt room not available
    GameManager --> GameUI : return "No such room"
  else room locked
    GameManager --> GameUI : return "The room is locked"
  else the room is unlocked && available
    GameManager -> Player : setPosition(<room>)
    deactivate Player
    GameManager --> GameUI : return "You are now in <room>"
  end
deactivate GameManager
GameUI --> User : display message
  deactivate GameUI

@enduml
