@startuml SaveInternalSequenceDiagram

!theme materia-outline

skinparam ArrowColor #DC143C
skinparam BackgroundColor #FFFFFF

skinparam titleBorderColor #DC143C
skinparam titleFontColor #DC143C

skinparam ActorBorderColor #DC143C
skinparam ActorFontColor #DC143C

skinparam ParticipantFontColor #DC143C
skinparam ParticipantBorderColor #DC143C

title Save - Internal Sequence Diagram

actor User
participant GameUI
participant GameManager
participant GameState
participant GameSaveServices

activate GameUI
User -> GameUI : insert "save" command

activate GameManager
GameUI -> GameManager : commandControl("save")
activate GameState
GameManager -> GameState : get game progress

activate GameSaveServices
GameState -> GameSaveServices : save game progress
GameSaveServices -> GameSaveServices : save operation
GameSaveServices --> GameState : return game progress
deactivate GameSaveServices

GameState --> GameManager : operation done
deactivate GameState

GameManager --> GameUI : return "Game saved"
deactivate GameManager

GameUI --> User : display message "Game saved"
deactivate GameUI

@enduml
