@startuml SaveInternalSequenceDiagram

!theme materia-outline

skinparam ArrowColor #DC143C
skinparam BackgroundColor #FFFFFF

skinparam titleBorderColor #DC143C
skinparam titleFontColor #DC143C

skinparam ActorBorderColor #DC143C
skinparam ActorFontColor #DC143C

skinparam ParticipantFontColor #DC143C
skinparam ParticipantBorderColor #DC143C

title Save - Internal Sequence Diagram

actor User
participant GameUI
participant GameManager
participant GameSaveServices
participant GameState

activate GameUI
User -> GameUI : insert "save" command

activate GameManager
GameUI -> GameManager : commandControl("save")

GameManager -> GameSaveServices : save the progress

activate GameState
GameSaveServices -> GameState : get game progress
GameState --> GameSaveServices : return game progress

GameSaveServices -> GameSaveServices : save operation

GameSaveServices --> GameManager : operation done
deactivate GameSaveServices

GameManager --> GameUI : return "Game saved"
deactivate GameManager

GameUI --> User : display message "Game saved"
deactivate GameUI

@enduml
